services:
  db:
    image: postgres
    container_name: tabloid-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tabloiddb
    ports:
      - "5432:5432"
    volumes:
      - tabloid_pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: tabloid-backend
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tabloiddb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
    container_name: tabloid-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  tabloid_pgdata:
